# docker-compose.yml
version: '3.10'

services:

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: assignment
    environment:
      DJANGO_SETTINGS_MODULE: core.settings

    command: bash -c "./run.sh"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

networks:
  default:
    name: assignment
